spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/studentsdb
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: Student API

server:
  port: 8080
