---
- hosts: all
  become: true
  tasks:

    - name: Update apt
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

    - name: Add Docker repository
      shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"

    - name: Update apt again
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker-ce
        state: latest

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Clone app repo
      git:
        repo: https://github.com/IrisLemeni/DockerApp.git
        dest: /home/ubuntu/app
        force: yes

    - name: Show git clone result
      debug:
        var: git_clone_result

    - name: Run docker compose
      shell: docker-compose up -d
      args:
        chdir: /home/ubuntu/app

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes
