name: Deploy with Ansible

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible rsync

      - name: Create Ansible inventory
        run: |
          mkdir -p ansible
          echo "[ec2]" > ansible/inventory.ini
          echo "${{ secrets.SERVER_IP }} ansible_user=${{ secrets.SSH_USERNAME }} ansible_ssh_private_key_file=~/.ssh/id_rsa ansible_ssh_common_args='-o StrictHostKeyChecking=no'" >> ansible/inventory.ini

      - name: Run Ansible playbook
        run: |
          ansible-playbook -i ansible/inventory.ini ansible/deploy.yml
